# Generated by Django 3.0.7 on 2020-06-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('subjects', models.CharField(max_length=100)),
                ('descriptions', models.CharField(max_length=400)),
            ],
        ),
    ]
