# Generated by Django 3.0.7 on 2020-06-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200606_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='descriptions',
            field=models.CharField(default='hey', max_length=400),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='emails',
            field=models.EmailField(default='hey@gmail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(blank=True, default='hey', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subjects',
            field=models.CharField(default='hey', max_length=100),
        ),
    ]
