# Generated by Django 3.0.7 on 2020-06-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200606_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='descriptions',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='emails',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subjects',
            field=models.CharField(max_length=100),
        ),
    ]
