# Generated by Django 3.0.7 on 2020-06-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200606_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subjects',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
