# Generated by Django 3.0.7 on 2020-06-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200606_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='descriptions',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
