# Generated by Django 3.0.7 on 2020-06-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200607_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='descriptions',
            field=models.TextField(default='This is the amazing place.', max_length=500),
        ),
    ]
