# Generated by Django 3.0.7 on 2020-06-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200607_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='movie_image',
            new_name='image',
        ),
    ]
